# Generated by Django 5.2.17 on 2026-09-28 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('submissions_close', models.DateTimeField()),
                ('results_publish_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=160)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='eventhub.event')),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='eventhub.event')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventhub.project')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='eventhub.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='eventhub.team')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='eventhub.track')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='eventhub.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_roles', to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(related_name='judges', to='eventhub.track')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.JSONField(default=dict)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='eventhub.judge')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='eventhub.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('judge', 'project'), name='unique_judge_project')],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_team_in_event'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_track_in_event'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_project_in_event'),
        ),
        migrations.AddConstraint(
            model_name='judge',
            constraint=models.UniqueConstraint(fields=('event', 'slug'), name='unique_judge_in_event'),
        ),
    ]
