# Generated by Django 5.2.17 on 2026-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
