# Generated by Django 5.2.17 on 2026-09-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0003_event_published_judge_invited_at_scoreaudit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='invite_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
