# Generated by Django 5.2.17 on 2026-09-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0004_judge_invite_expires_at_judge_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rubric',
            field=models.JSONField(default=dict),
        ),
    ]
