# Generated by Django 5.2.17 on 2026-09-28 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0006_judge_unique_event_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='voting_access',
            field=models.CharField(choices=[('authenticated', 'Authenticated'), ('email', 'Email verified'), ('open', 'Open link')], default='authenticated', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='voting_closes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='voting_opens',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhub.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhub.project')),
            ],
        ),
        migrations.CreateModel(
            name='PublicVoteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_key', models.CharField(max_length=180)),
                ('action', models.CharField(max_length=32)),
                ('observed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhub.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhub.project')),
            ],
        ),
        migrations.CreateModel(
            name='PublicVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_key', models.CharField(max_length=180)),
                ('receipt', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_votes', to='eventhub.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_votes', to='eventhub.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'voter_key'), name='unique_public_vote_per_voter_event')],
            },
        ),
    ]
