# Generated by Django 5.2.17 on 2026-09-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0007_event_voting_access_event_voting_closes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicActionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_key', models.CharField(max_length=180)),
                ('action', models.CharField(max_length=20)),
                ('observed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhub.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'actor_key', 'action', 'created_at'], name='eventhub_pu_event_i_82c2ff_idx')],
            },
        ),
    ]
