# Generated by Django 5.2.17 on 2026-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0008_publicactionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
