# Generated by Django 5.2.17 on 2026-09-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0009_event_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('open', 'Open link'), ('email', 'Email')], max_length=10)),
                ('identity', models.CharField(blank=True, max_length=254)),
                ('secret_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventhub.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'email')), fields=('event', 'kind', 'identity'), name='unique_voter_access_identity')],
            },
        ),
    ]
