# Generated by Django 5.2.17 on 2026-09-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0011_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeParticipationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('review_count', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('signature', models.CharField(max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventhub.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventhub.judge')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'judge'), name='unique_judge_participation_record')],
            },
        ),
    ]
