# Generated by Django 5.2.17 on 2026-09-28 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0013_judgecertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_status', models.CharField(blank=True, max_length=50)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventhub.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'kind'), name='unique_event_webhook_kind')],
            },
        ),
    ]
