# Generated by Django 5.2.17 on 2026-09-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0014_webhookdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
    ]
