# Generated by Django 5.2.17 on 2026-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0015_event_custom_questions_project_custom_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
